---

#ansible-playbook template.yml

- name: run tasks in each env
  hosts: amineamout.com
  connection: local
  tasks:
   - name: create folder outputs
     file:
      path: "{{ item }}"
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0777
      recurse: yes
     with_items:
      - '/home/dev/ansible/output'
      - '/home/dev/ansible/output/qualif'
      - '/home/dev/ansible/output/prod'
      - '/home/dev/ansible/output/dev'
   - name: template file onto remote host
     template:
      src: "{{ playbook_dir }}/templates/spark/spark-submit.sh.j2"
      dest: /home/dev/ansible/{{ env.short }}/output/spark-submit.sh
      owner: jenkins
      group: jenkins
      mode: 0777
     vars:
     with_items:
      - short: qualif
        long: qualification
        target: qualif.amineamout.com
      - short: prod
        long: production
        target: prod.amineamout.com
      - short: dev
        long: development
        target: dev.amineamout.com
     loop_control:
       loop_var: env
